### ISSUE TITLE
What are the problems we want to solve?

### ISSUE THREAD

**Issue by huhuanming** [huhuanming/UploadKit#1]
1. A light and fast upload framework for iOS and macOS without any third-party library, and it is so strong to resolve any exception and prevent any memory leak.
2. Provide a simplified interface and make clouds easier to work with and switch between.
3. Mocks make testing and integrating a breeze.
4. Swift 3 Only.
5. Supporting both CocoaPods and Carthage.(Support Lately)
6. Unit tests.(Travis Ci)

**Comment by hyichao** [comment]
4. provide a swift version upload framework implementation supporting increasing swift projects.

**Comment by hyichao** [comment]
1. provide a swift version uploading implementation to better support increasing swift projects.

**Comment by huhuanming** [comment]
Good!!! and any more ?

**Comment by huhuanming** [comment]
Maybe, it is Swift 3 only.

**Comment by hyichao** [comment]
Swift 3 only means we could only support iOS 9.0+ with Xcode 8.0+ (Refer to Alamofire). I think that make sense, as swift 2.0+ && swift 3.0+ shares great difference. Therefore, I vote for swift 3 only.

**Comment by huhuanming** [comment]
Swift 3 is compatible with **iOS 8** and newer, so I vote for swift 3 too.

**Comment by hyichao** [comment]
I'm not familiar with Carthage. I'm wondering if we could simply start with a CocoaPods project according to this [guide page](https://guides.cocoapods.org/making/making-a-cocoapod.html) and when it comes to a stable version we then add Carthage support?

**Comment by huhuanming** [comment]
Okay,  i note it

**Comment by huhuanming** [comment]
Is there anything else you'd like to add?
if not, we need to freeze requirements.

**Comment by hyichao** [comment]
What if we define some modules before coding?

**Comment by huhuanming** [comment]
Yep,  the next thing is design.

![image](https://cloud.githubusercontent.com/assets/5743863/19259451/529b0e5a-8fb4-11e6-900f-734947f4770d.png)

**Comment by hyichao** [comment]
Great. That's professional man. Then lets start the design section! If there is anything we need to add we could still come back to this "Idea" section.

**Comment by huhuanming** [comment]
Okay, temporarily close this issue.
