### ISSUE TITLE
Design for the UploadKit

### ISSUE THREAD

**Issue by huhuanming** [huhuanming/UploadKit#2]
1. What tools are used for the design?
2. When should we release the fundamental design?(The design should includes most of features about [issue#1](https://github.com/huhuanming/UploadKit/issues/1))
3. Finally, review the design of each other and merge every advantages.

Everyone can directly update this question.

**Comment by hyichao** [comment]
Q1 is not clear for me. Could you please explain the meaning of "tools", i.e. raise some options?

**Comment by huhuanming** [comment]
For example, some UML tools, or others can describe the application architecture.

I have no idea for it.

**Comment by hyichao** [comment]
I don't think we need UML. I've read some blogs and books (just rough reading) of UML and I think its more beneficial to use UML when there is business logic. But in our case, it seems like we don't need to upgrade the work load.

**Comment by huhuanming** [comment]
Sorry, but you mean, UML, or XML? 
Ans: UML, wrong auto correct...

**Comment by huhuanming** [comment]
But i cannot find the best way to describe the architecture.
Or, mind maps?

**Comment by hyichao** [comment]
Yep. We might simply use XMind (this is the one I am using) to produce some flowchart (not necessarily formal, but should be clear enough to explain the structure). As we just start this project. the structure may be very simple for  a while ... so just start with simple things and move on.

**Comment by huhuanming** [comment]
Awsome! you mean the best way is a way that you love to.
And we need to appoint a time.

**Comment by hyichao** [comment]
I hope we would finish design by next Friday (Oct 21st), and design includes: 1. modules; 2. interfaces. To be honest I do appreciate the interface of [qiniu_upload](https://github.com/huhuanming/qiniu_upload), however, in this project using swift, we might pay some efforts to use closures and method chaining. As for modularization, I need to listen to your idea.

maybe the interface should be something like

```
Uploader.sharedInstance()
.uploadFile(someFile)
.onSuccess{a closure of what should do if upload succeed}
.onFailure{a closure of what should do if upload fail}
```

**Comment by huhuanming** [comment]
Well I agree with it, but I am sorry that I have no answer now.

We need to read  a lot of the best practice of others in Swift, and If we have some idea, it is better to post it on here before the deadline.

Because we should make a decision on deadline day.

**Comment by hyichao** [comment]
What do you think if we create the project and write some method definition without implementation? i.e. we create a project and create some basic classes with basic methods and once we found something useful we then modify the codes? 

I'm not sure if this works for two-person team, please tell me your idea. I do have something in mind but I don't know how to express them by words... There are only codes in mind... Or, should I draw the flowchart?

**Comment by hyichao** [comment]
I roughly draw a flowchart with powerpoint (which is not cool anyway...). And the structure is basically about two classes: UploadFile and Uploader. UploadFile can be init with UIImage or NSData or some local file and we could use extension to implement (extension in swift gets powerful). As for uploader, it is indeed an adapter for multiple uploader of different cloud services. I'm not sure how many differences among those cloud services and hope they are similar. And for upload completion strategy we need further discussion.

![flowchart-4-uploadkit](https://cloud.githubusercontent.com/assets/8193182/19377052/96011262-9215-11e6-9397-714e6bbc359c.png)

**Comment by huhuanming** [comment]
Well, in the moment the only thing we are talking about is architecture included classes, method definition, interface, and others, and this is the basis of our project.

Then, in different cloud services, we should know the differences based on sufficient survey.

And, if you cannot express your ideas well at such ways,  you could use a simplified pseudo-code. Either way will do.

Do not be in a hurry to code,  more reading than less coding.

**Comment by hyichao** [comment]
Hey bro, it seems like we have to delay the design deadline.  As you are in some personal issue right now but I cannot work this out without your guidance.. I do read the document of UP, qiniu and AWS roughly but don't know which part to focus on..

**Comment by huhuanming** [comment]
During these day, I have to get back to work and I am under a deadline of my company. 

I'm so sorry about it.

Later this evening I will submit my plan for UploadKit and the next day, we can discuss the plan in available time.

Maybe, we need an extension of time.

**Comment by huhuanming** [comment]
### General Upload

`UploadTask: UploadTaskProtocol`

A general upload process includes the following tips：
1. A NSMutableURLRequest  is assembled by Adding URL, HTTP Headers and HTTP Body
2. Define a NSURLSessionTask to process the NSMutableURLRequest
3. Processing the return value named NSURLResponse of NSURLSessionTask

`UploadTask` should include a pre-function

### Multipart Upload

`MutipartUploadTask: UploadTaskProtocol`
An multipart upload process includes the following tips：
1. Initiate multipart upload (an web API request)
2. Upload part(Mutiple general upload  )
3. Complete multipart upload(An web API request)
4. Abort multipart upload (If needed, an web API request)

### Upload Queue

`UploadQueue`
1. Concurrency control
2. Priority of its upload.
3. Immutable. Once it has been set, it cannot be change now.(if needed)
4. The basic unit is a class that implement the methods of a protocol named UploadTaskProtocol

### Similarities and Differences In Cloud Service
1. Different URL and HTTP Headers, But the same HTTP Body
2. The same NSURLSessionTask and NSURLResponse, But different pre-operation and post-operation
3. Different multipart upload api, but the same process

### Architecture

The similarities are the codes and the differences are  protocols.

(to be continue...)

**Comment by hyichao** [comment]
When will the "to be continued" part completed bro?  :)

**Comment by huhuanming** [comment]
sorry, I’m working on-it tonight.

**Comment by huhuanming** [comment]
Can we stick with that point about design on #3 ?

Code is the best way to show our idea.
